aws:
  s3:
    bucket:
      stack.auto: false
      name: gitdeun
      region: ap-northeast-2
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretAccessKey: ${S3_SECRET_KEY}

spring:
  config:
    activate:
      on-profile: s3Bucket
