server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${MYSQL_PROD_URL}  # MySQL 데이터베이스 URL
  data:
    redis:
      host: gitdeun-redis
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://api.gitdeun.site/login/oauth2/code/google
          github:
            client-id: ${GITHUB_PROD_CLIENT_ID}
            client-secret: ${GITHUB_PROD_CLIENT_SECRET}
            redirect-uri: https://api.gitdeun.site/api/auth/github/callback


jwt:
  access-expired: 1800 # 30분(초 단위: 0.5 * 60 * 60)
  refresh-expired: 604800  # 7일(초 단위: 7 * 24 * 60 * 60)

app:
  front-url: https://gitdeun.site
  cookie:
    secure: true
    same-site: None
  oauth:
    github:
      connect-redirect-uri: https://api.gitdeun.site/api/auth/connect/github